local syntax = require "core.syntax"

syntax.add {
  files = {"%.xls$"},
  comment = "//",
  patterns = {
    { pattern = { "//", "\n" },                            type = "comment"  },
    { pattern = { "#", "\n"},                              type = "comment"  }, -- there is no standardised preprocessor colour unfortunately
    { pattern = { '"', '"', '\\' },                        type = "string"   },
    { pattern = "'\\?[^']'",                               type = "string"   },
    { pattern = "-?0b[01]+",                               type = "number"   },
    { pattern = "-?0q[0-3]+",                              type = "number"   },
    { pattern = "-?0s[0-5]+",                              type = "number"   },
    { pattern = "-?0o[0-7]+",                              type = "number"   },
    { pattern = "-?0d[0-9]+",                              type = "number"   },
    { pattern = "-?0x[0-9a-fA-F]+",                        type = "number"   },
    { pattern = "-?0n[0-9a-zA-Z]+",                        type = "number"   },
    { pattern = "-?[0-9%.]+",                              type = "number"   },
    { pattern = "-?%.?%d+",                                type = "number"   },
    { pattern = "[%a_][%w_%-+/*%%&:@=><?!]* *%f[(]",       type = "function" },
    { pattern = "%f[|]%f[>] *[%a_][%w_%-+/*%%&:@=><?!]*",  type = "function" },
    { pattern = "[%a_][%w_%-+/*%%&:@=><?!]*%f[%*]",        type = "symbol"   },
    { pattern = "[%a_][%w_%-+/*%%&:@=><?!]*",              type = "symbol"   },
  },
  symbols = {
    ["implement"]  = "keyword",
    ["impl"]       = "keyword",
    ["extern"]     = "keyword",
    ["if"]         = "keyword",
    ["else"]       = "keyword",
    ["operator"]   = "keyword",
    ["cdecl"]      = "keyword",
    ["fastcc"]     = "keyword",
    ["coldcc"]     = "keyword",
    ["tailcc"]     = "keyword",
    ["webkitjscc"] = "keyword",
    ["win64cc"]    = "keyword",
    ["while"]      = "keyword",
    ["dowhile"]    = "keyword",
    ["label"]      = "keyword",
    ["jump"]       = "keyword",
    ["volatile"]   = "keyword",
    ["mutable"]    = "keyword",
    ["struct"]     = "keyword",
    ["typedef"]    = "keyword",
    ["alias"]      = "keyword",
    ["break"]      = "keyword",
    ["continue"]   = "keyword",
    ["return"]     = "keyword",
    ["c-variadic"] = "keyword",
    ["variadic"]   = "keyword",
    ["setjump"]    = "keyword",
    ["longjump"]   = "keyword",
    ["funcdef"]    = "keyword",
    ["macro"]      = "keyword",
    ["dword"]      = "keyword2",
    ["word"]       = "keyword2",
    ["byte"]       = "keyword2",
    ["boole"]      = "keyword2",
    ["void"]       = "keyword2",
    ["sdword"]     = "keyword2",
    ["sword"]      = "keyword2",
    ["sbyte"]      = "keyword2",
    ["jumpbuf"]    = "keyword2",
    ["valist"]     = "keyword2",
    ["fn&"]        = "keyword2",
    ["label&"]     = "keyword2",
  }
}
